# Generated by Django 5.0.7 on 2024-07-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_tc_user_upi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='upi_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
