# Generated by Django 5.0.7 on 2024-07-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_spamdetectionmodel_transactionpatterndetectionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerId', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('CreditScore', models.IntegerField()),
                ('CustLocation', models.CharField(max_length=255)),
                ('CustGender', models.CharField(max_length=7)),
                ('CustAge', models.IntegerField()),
                ('CustAccountBalance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionID', models.CharField(max_length=255)),
                ('CustomerID', models.CharField(max_length=255)),
                ('CustomerDOB', models.DateField()),
                ('CustGender', models.CharField(max_length=7)),
                ('CustLocation', models.CharField(max_length=255)),
                ('CustAccountBalance', models.FloatField()),
                ('TransactionDate', models.DateField()),
                ('TransactionTime', models.BigIntegerField()),
                ('TransactionAmount', models.FloatField()),
            ],
        ),
    ]
