# Generated by Django 5.0.7 on 2024-07-15 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customeraccount_transactionmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpamDetectionModel',
        ),
        migrations.DeleteModel(
            name='TransactionPatternDetectionModel',
        ),
    ]
