# Generated by Django 5.0.7 on 2024-07-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_spamdetectionmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='receiver_upi',
            field=models.CharField(default='default_upi', max_length=255),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='sender_upi',
            field=models.CharField(default='default_upi', max_length=255),
        ),
    ]
