# Generated by Django 5.0.7 on 2024-07-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_transactionmodel_receiver_upi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmodel',
            name='receiver_upi',
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='sender_upi',
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='email',
            field=models.EmailField(default='defaultemail@email.com', max_length=255),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='phnno',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='receiver_phno',
            field=models.IntegerField(default=1234),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='sender_phnno',
            field=models.IntegerField(default=1234),
        ),
    ]
