# Generated by Django 5.0.7 on 2024-07-15 17:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_lockingsystemmodel_banking_app_creditcard_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreditCard',
            new_name='CreditCardModel',
        ),
        migrations.RenameModel(
            old_name='DebitCard',
            new_name='DebitCardModel',
        ),
        migrations.RenameModel(
            old_name='NetBankingDetails',
            new_name='NetBankingDetailsModel',
        ),
    ]
