# Generated by Django 5.0.7 on 2024-07-17 18:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_creditcardmodel_pin_debitcardmodel_pin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraccount',
            old_name='CreditScore',
            new_name='credit_score',
        ),
        migrations.RenameField(
            model_name='customeraccount',
            old_name='CustAccountBalance',
            new_name='customer_account_balance',
        ),
        migrations.RenameField(
            model_name='customeraccount',
            old_name='CustAge',
            new_name='customer_age',
        ),
        migrations.RenameField(
            model_name='customeraccount',
            old_name='CustGender',
            new_name='customer_gender',
        ),
        migrations.RenameField(
            model_name='customeraccount',
            old_name='CustLocation',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='customeraccount',
            old_name='CustomerId',
            new_name='customer_location',
        ),
        migrations.RenameField(
            model_name='transactionmodel',
            old_name='CustAccountBalance',
            new_name='customer_account_balance',
        ),
        migrations.RenameField(
            model_name='transactionmodel',
            old_name='CustLocation',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='transactionmodel',
            old_name='CustomerID',
            new_name='receiver_upi',
        ),
        migrations.RenameField(
            model_name='transactionmodel',
            old_name='TransactionID',
            new_name='sender_upi',
        ),
        migrations.RenameField(
            model_name='transactionmodel',
            old_name='TransactionAmount',
            new_name='transaction_amount',
        ),
        migrations.RenameField(
            model_name='transactionmodel',
            old_name='TransactionTime',
            new_name='transaction_time',
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='CustGender',
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='CustomerDOB',
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='TransactionDate',
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='customer_dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='customer_gender',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='customer_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='transaction_id',
            field=models.CharField(default=1234, max_length=255),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('receiver', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='VirtualNetBankingDetailsModel',
        ),
    ]
