# Generated by Django 5.0.7 on 2024-07-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_creditscore_customeraccount_credit_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='transaction_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='transaction_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
