# Generated by Django 5.0.7 on 2024-07-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_transactionmodel_transaction_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='device_name',
            field=models.CharField(default='abc', max_length=255),
        ),
    ]
