# Generated by Django 5.0.7 on 2024-07-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_transactionmodel_device_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LockingSystemModel',
        ),
        migrations.AddField(
            model_name='creditcardmodel',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debitcardmodel',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='netbankingdetailsmodel',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
