# Generated by Django 5.0.7 on 2024-07-17 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_delete_lockingsystemmodel_creditcardmodel_is_locked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='report',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='report',
            name='receiver_upi',
            field=models.CharField(default='upi@upi', max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.transactionmodel'),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='receiver_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='accounts.customeraccount'),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='report_images/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='report_images/'),
        ),
    ]
