# Generated by Django 5.0.7 on 2024-07-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_creditcardmodel_is_locked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='receiver_upi',
            field=models.CharField(max_length=255),
        ),
    ]
