# Generated by Django 5.0.7 on 2024-07-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpamPrediction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spamdetectionmodel',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
